spring:
  liquibase:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS CASH_CUB
    user: sa
    password: sa
    default-schema: cash_cub
    liquibase-schema: cash_cub
  r2dbc:
    url: r2dbc:h2:mem:///db?options=DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE;SCHEMA=cash_cub
    username: sa
    password: sa
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/default